name = "tmp-worker"
main = "src/index.ts"
compatibility_date = "2024-03-11"
minify = true

kv_namespaces = [
  { binding = "KV", id = "ac8c25f7b58f46aab78361ce41026b63", preview_id= "ac8c25f7b58f46aab78361ce41026b63" }
]

[ai]
binding = "AI"