config:
  cloudflare-workers-ai:accountId: 24725f46259aa3c2a1d7810649cd7428
  cloudflare-workers-ai:domain: atxyall.com
  cloudflare-workers-ai:zoneId: 10417f0f3cdfae4db9c951209933f4e0
  cloudflare:apiToken:
    secure: AAABANp+rmQG3ww3uXNR1TR9o8gRnEE8+iIKg8wFuSAHzU2a+86ThWnHET+Kjbesu0OchNvWsuW7AzcmcUvm4fAK6s/BhPDF
