name = "worker-wrangler"
main = "src/worker.ts"
compatibility_date = "2024-06-01"
minify = true

kv_namespaces = [{  "binding" = "kv_wrangler",  "id" = "3dfdfc3f927c4698a3fbac85363eb419" }]

[ai]
binding = "AI"